server:
  port: 3500
spring:
  application:
    name: crm_config_server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/defers/crm_app_microservices-configserver
          clone-on-start: true

customers:
  value: 10