spring:
  profiles:
    active: dev

---

server:
  port: 3500
spring:
  application:
    name: crm_config_server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/defers/crm_app_microservices-configserver-properties.git
          clone-on-start: true
          refresh-rate: 300
  config:
    activate:
      on-profile: dev
management:
  endpoints:
    web:
      exposure:
        include: "*"